dist: xenial
sudo: false
language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8
  - openjdk9
#  - openjdk11

before_install:
  # Parameters used during release
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

  # update all git submodule
  - git submodule init && git submodule update --init --recursive --remote --merge

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn jacoco:report coveralls:report

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

# safelist
  only:
    - master
    - develop
    - release

jobs:
  include:
  - stage: develop
    name: "Build and Unit Testing the develop & PR branch"
    if: (branch = master OR type = pull_request) AND commit_message !~ /^(prepare release ([0-9\.]+))$/
    jdk: openjdk8
    install: true
    script:
      - ./mvnw -B -nsu -s ./travis/settings.xml -N io.zipkin.centralsync-maven-plugin:\
        centralsync-maven-plugin:sync -Dsync.dryRun -DskipTests=false

  - stage: snapshot
    name: "Deploy Snapshot to Maven repo"
    if: branch = master AND type != pull_request AND commit_message !~ /^(prepare release ([0-9\.]+))$/
    jdk: openjdk8
    install: true
    script:
      - ./mvnw -B -nsu -s ./travis/settings.xml -P release -pl -:djanta-benchmark -DskipTests=true deploy

  - stage: release
    name: "Release to OSS SonaType"
    if: tag =~ /^[0-9\.]+$/
    jdk: openjdk8
    install: true
    script:
      - ./mvnw -B -nsu -s ./travis/settings.xml -P release -pl -:djanta-benchmark -DskipTests=true deploy

  - stage: sync
    name: "Sync with Maven Central"
    if: tag =~ /^[0-9\.]+$/
    jdk: openjdk8
    install: true
    script:
      # this step can take an inordinate amount of time, so the wait should push it to 30 minutes
      - travis_wait 30 ./mvnw -B -nsu -s ./travis/settings.xml -N io.zipkin.centralsync-maven-plugin:centralsync-maven-plugin:sync

notifications:
  email:
    recipients:
      - "$GH_USER_EMAIL"
    on_success: change  # default: change
    on_failure: always  # default: always

#env:
#  global: