dist: xenial
sudo: false
language: java

# Provided Travis-ci additional services
services:
  - docker

cache:
  directories:
    - $HOME/.m2

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
#    - /^[0-9]/

  # safelist
  only:
    - master
    - develop
    - release
    - /^((rc|v|version|release|tag)(-)?)?([0-9\.]+)((-)?(patch|beta|alpha))?$/

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

before_install:
  # Parameters used during release
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

  # Update all git submodule (No need this manual submodule update ...)
  ## Uncomment the line below if the auto update submodule has not been activated by travis
  #- git submodule init && git submodule update --init --recursive --remote --merge
  - git submodule update --init --recursive --remote --force # Force update the project submodule if existed

  ## Running this comment is mandatory to resolve the follwing issue: "No plugin found for prefix 'help' in the current project"
  ## Otherwise this command will fail: "./mvnw -o help:evaluate -N -Dexpression=project.version | sed -n '/^[0-9]/p'"
  ## CREDIT: https://stackoverflow.com/questions/26364608/why-is-there-the-error-no-plugin-found-for-prefix-help-in-the-current-project
  - mvn -X help:effective-pom

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  ##
  # Install codeclimate tools. Credit: https://github.com/Milfist/Configure-TravisCI-CodeClimate-Maven-Java
  ##
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  ##
  # Install codeclimate tools. Credit: https://github.com/Milfist/Configure-TravisCI-CodeClimate-Maven-Java
  ##
  - ./cc-test-reporter format-coverage -d -t jacoco ./target/coverage-reports/jacoco.xml
  - ./cc-test-reporter upload-coverage -d

after_success:
#  - mvn jacoco:report coveralls:report
  - mvn versions:display-dependency-updates
  - mvn versions:display-plugin-updates

matrix:
  include:
  - jdk: openjdk8
  - jdk: openjdk9
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  - jdk: openjdk10
    before_install:
      - sudo rm "${JAVA_HOME}/lib/security/cacerts"
      - sudo ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  - jdk: openjdk11

stages:
  - name: develop
    if: (branch = develop AND type != pull_request) AND commit_message !~ /^(prepare release ([0-9\.]+))$/
  - name: snapshot
    if: branch = master AND type != pull_request AND commit_message !~ /^(prepare release ([0-9\.]+))$/

  - name: release
    if: branch = release AND type != pull_request AND commit_message !~ /^(prepare release ([0-9\.]+))$/

  - name: deploy
    if: tag =~ /^((rc|v|version|release|tag)(-)?)?([0-9\.]+)((-)?(patch|beta|alpha))?$/
  - name: sync
    if: tag =~ /^((rc|v|version|release|tag)(-)?)?([0-9\.]+)((-)?(patch|beta|alpha))?$/

jobs:
  include:
  - stage: develop
    name: "Build and Unit Testing the develop & PR branch"
    jdk: openjdk8
    install: true
    script:
      #- ./mvnw -B -nsu -s ./.mvn/settings.xml -N io.zipkin.centralsync-maven-plugin:centralsync-maven-plugin:sync -Dsync.dryRun -DskipTests=false deploy
      - ./mvnw -B -X -nsu -s ./.mvn/settings.xml -N -Psite site:site -Dsync.dryRun -DskipTests=false

  - stage: snapshot
    name: "Deploy Snapshot to Maven repo"
    jdk: openjdk8
    install: true
    script:
      # Deploy the snapshot to sonatype
      - ./mvnw -B -nsu -s ./.mvn/settings.xml -Psonatype -DskipTests=true deploy

      # Deploy the snapshot to github registry
      - ./mvnw -B -nsu -s ./.mvn/settings.xml -P!sonatype,github -DskipTests=true deploy

  - stage: deploy
    name: "Release to OSS SonaType"
    jdk: openjdk8
    install: true
    script:
      #- ./mvnw -B -nsu -s ./.mvn/settings.xml -P release -DskipTests=true deploy
      - echo "Just deploy the tagged version"

  - stage: sync
    name: "Sync with Maven Central"
    jdk: openjdk8
    install: true
    script:
      # this step can take an inordinate amount of time, so the wait should push it to 30 minutes
      - travis_wait 30 ./mvnw -B -nsu -s ./.mvn/settings.xml -P sonatype -N io.zipkin.centralsync-maven-plugin:centralsync-maven-plugin:sync

notifications:
  email:
    recipients:
      - $GH_USER_EMAIL
    on_success: change  # default: change
    on_failure: always  # default: always