#
# Copyright 2019-2020 DJANTA, LLC (https://www.djanta.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed toMap in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md

###
# Github Workflow Help: https://help.github.com/en/actions/reference/events-that-trigger-workflows
#   https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes
###

name: Build

# On push event ...
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    if: (startsWith(github.event.head_commit.message, 'prepare release') == false)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['1.8']
        os: [ubuntu-latest]
#        fail-fast: false
#    if: github.event_name == 'push' && startsWith(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
#      - name: Check Commit Type
#        uses: gsactions/commit-message-checker@v1
#        with:
#          pattern: '\[[^]]+\] .+$'
#          flags: 'gm'
#          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
#      - name: Check Line Length
#        uses: gsactions/commit-message-checker@v1
#        with:
#          pattern: '^[^#].{74}'
#          error: 'The maximum line length of 74 characters is exceeded.'
#      - name: Check for Resolves / Fixes
#        uses: gsactions/commit-message-checker@v1
#        with:
#          pattern: '^.+(Resolves|Fixes): \#[0-9]+$'
#          error: 'You need at least one "Resolves|Fixes: #<issue number>" line.'
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
#      - name: get commit message
#        run: |
#          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: Checking out - (${{ matrix.os }})
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true
      - name: Submodules Sync - (${{ matrix.os }})
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote --merge --force --depth=3
      - name: Gpg initialization - (${{ matrix.os }})
        shell: bash
        run: |
          echo "GnuGpg initialization step ..."

          TMPDIR=${TMPDIR:-$(dirname $(mktemp))}
          KEYSTORE=${KEYSTORE:-$TMPDIR/.keystore}
          IN_PUB=$(pwd)/.gnugp/deploy/pubring.gpg.asc
          IN_PRV=$(pwd)/.gnugp/deploy/secring.gpg.asc
          OUT_PUB=$KEYSTORE/pubring.gpg.enc
          OUT_PRV=$KEYSTORE/secring.gpg.enc

          mkdir -pv $KEYSTORE

          gpg --decrypt --yes --batch --passphrase=${{ secrets.GPG_MASTER_PASSWORD }} --output=$OUT_PUB $IN_PUB
          gpg --decrypt --yes --batch --passphrase=${{ secrets.GPG_MASTER_PASSWORD }} --output=$OUT_PRV $IN_PRV

          gpg --yes --batch --import $OUT_PUB >/dev/null 2>&1;
          gpg --yes --batch --import $OUT_PRV >/dev/null 2>&1;

          rm -rfv $KEYSTORE
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - name: GitHub credentials configuration - ${{ matrix.os }} with version ${{ matrix.version }}
        shell: bash
        run: |
          echo "GITHUB_TOKEN = $GITHUB_TOKEN, GITHUB_TOKEN Secret: ${{ secrets.GITHUB_TOKEN }}"
          git config user.name "${{ secrets.GH_USER }}"
          git config user.email "${{ secrets.GH_USER_EMAIL }}"
          git config credential.helper "store --file=.git/credentials"
          echo "https://${{ secrets.GITHUB_TOKEN }}:@github.com" > .git/credentials
      - name: Maven Build (Clean & verify) - ${{ matrix.os }} with version ${{ matrix.version }}
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GH_USER }}
        run: |
          ./mvnw -B -X -s $(pwd)/.mvn/settings.xml -Dsync.dryRun -DskipTests=false clean verify
          ./mvnw -X -B -s $(pwd)/.mvn/settings.xml -Prelease,github,-sonatype -DskipTests=true clean deploy
          ./mvnw -X -B -s $(pwd)/.mvn/settings.xml -Prelease,sonatype -DskipTests=true clean deploy
#          mvn -X help:effective-pom
