#
# Copyright 2019-2020 DJANTA, LLC (https://www.djanta.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed toMap in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Java Build

# On push event ...
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.8'
        os:
          - ubuntu-latest
          #- ubuntu-16.04
          #- ubuntu-18.04
    steps:
      - name: Checking branch
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote --merge --force --depth=1
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - name: Maven Build (Clean & verify) on ${{ matrix.os }} with version ${{ matrix.version }}
        run: |
          ./mvnw -B -nsu -s .mvn/settings.xml -N -Psonatype -Dsync.dryRun -DskipTests=false clean test verify

  # Deploy the current snapshot and install it
  snapshot:
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Create & Publish the snapshot TO (Sonatype & Github)
        if: github.branch == 'master' && github.event_name == 'push'
        run: |
          ./mvnw -B -nsu -s .mvn/settings.xml -N -Psonatype -DskipTests=true clean deploy
          ./mvnw -B -nsu -s .mvn/settings.xml -N -P!sonatype,github -DskipTests=true clean deploy
