name: Java Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [ '1.8' ]
        os:
          - ubuntu-latest
          - ubuntu-16.04
          - ubuntu-18.04
    steps:
      - name: Checking branch
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote --merge --force --depth=1
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - name: Build with Maven (Clean & verify)
        run: |
          ./mvnw -B -nsu -s .mvn/settings.xml -N -Psonatype -Dsync.dryRun -DskipTests=false clean test verify

