#
# Copyright 2019-2020 DJANTA, LLC (https://www.djanta.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed toMap in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Master

# On push event ...
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
jobs:
  # Deploy the current snapshot and install it
  snapshot:
#    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['1.8']
        os: [ubuntu-latest]
    steps:
      - name: Checking branch
        uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote --merge --force --depth=3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - name: Create & Snapshot to (Sonatype & Github)
#        if: github.branch == 'master' && (github.event_name == 'push' || github.event_name == 'create')
        env:
#          GPG_MASTER_PASSWORD: ${{ secrets.MASTER_PASSWORD }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        run: |
          git config user.name "${{ secrets.GH_USER }}"
          git config user.email "${{ secrets.GH_USER_EMAIL }}"
          git config credential.helper "store --file=.git/credentials"
          echo "https://${{ secrets.GITHUB_TOKEN }}:@github.com" > .git/credentials

#         Openssl configuration
#          openssl aes-256-cbc -salt -k $GPG_MASTER_PASSWORD -in $(pwd)/.gnupg/deploy/secring.gpg -out $tmp/deploy/secring.gpg.enc
#          openssl aes-256-cbc -k $GPG_MASTER_PASSWORD -in $(pwd)/.gnupg/deploy/pubring.gpg -out $tmp/deploy/pubring.gpg.enc

#         Exporting gpg configuration
#          export GPG_TTY=$(tty)

#          gpg --keyserver pool.sks-keyservers.net --recv-keys ${{ secrets.GPG_KEYID }}
          which gpg
          mvn -X -B clean
#          ls -als $(pwd)/target/
#          echo ${{ secrets.PGP_PRIVATE_KEY }} | gpg --import
#          mvn -X help:effective-pom
#          ./mvnw -X -B --errors -s $(pwd)/.mvn/settings.xml -Prelease,github,-sonatype -Dgpg.executable=gpg clean deploy
#          ./mvnw -B --errors -s $(pwd)/.mvn/settings.xml -Prelease,sonatype clean deploy
